### ISSUE TITLE
Cannot access Rolaguard from other PC

### ISSUE THREAD

**Issue by pe1mew** [Argeniss-Software/rolaguard#11]
**Describe the bug**
A browser on a PC on the same network as the PC with Rolaguard cannot login at Rolaguard while accessing from localhost is no problem. The progress circle keeps circling

**To Reproduce**
1. Start browser on other PC
2. go to <ip-address>:30000
3. login with admin credentials

**Expected behavior**
Successfull login.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/11438883/106377612-8b6b9c00-639e-11eb-98d5-aa066384ad1e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 85.0

**Comment by leareyes22** [comment]
Hi! Sorry for the delay.
Before launch the application with docker-compose up, if you are working with two or more computers at the same network, you have to modify the next environment variables on the frontend.env file:
window.RUNTIME_API_HOST= 'http://localhost:30000/api/v1.0/';
window.RUNTIME_WS_HOST= 'http://localhost:30000/';
In place of localhost, you have to put the IP address of the computer that is working as a server.
This change is in order to allow the access to the application from differents computers at the same network.
