### ISSUE TITLE
Cannot remove gateway entries from test network

### ISSUE THREAD

**Issue by pe1mew** [Argeniss-Software/rolaguard#13]
**Describe the bug**
After setting up the system, the default collector is removed. 
The gateways that have been "heard" by the system cannot be removed and keep cluttering mij system.

**Expected behavior**
A way to remove unwanted or faulty data.

**Comment by miguelstorani** [comment]
Hi there! sorry for the delay. In order to get the system up and running without any unwanted data you'll have to build your own database docker image (or generate your own database schema) from the [postgres project](https://github.com/Argeniss-Software/rolaguard_postgres) files.

To prevent the test network from loading you can delete lines [88-89](https://github.com/Argeniss-Software/rolaguard_postgres/blob/3adedc67e5f0b79e26516ee7f9c6ba340f452e59/2-data.sql#L88) from the file [2-data.sql](https://github.com/Argeniss-Software/rolaguard_postgres/blob/master/2-data.sql), and then build the image with `docker build -t rolaguardcommunity/postgres:latest . `. After building the new image you need to stop the system and delete the already created database by removing the `~/rolaguard/db-data` folder in your system, please note that this action will delete all of your database data. Once everything is done, run the system again and it will start without any preloaded network.

This is the most straightforward way to do what you need, but will delete all of your already generated data (including users).

**Comment by cyones** [comment]
A button to archive devices and gateways was added.
